AddCSLuaFile( "cl_init.lua" )
AddCSLuaFile( "shared.lua" )
include( "shared.lua" )

util.AddNetworkString("ResistanceRP.PlayIntroduction")
util.AddNetworkString("ResistanceRP.Debug.RemovePanels")
util.AddNetworkString("ResistanceRP.LoadMainMenu")
util.AddNetworkString("ResistanceRP.CreateCharacter")
util.AddNetworkString("ResistanceRP.CreateNewUser")
util.AddNetworkString("ResistanceRP.SendPlayerInfo")
